version: '3'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./back-end:/app
    depends_on:
      - database
    command: "dev"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./front-end:/app

  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cashforce_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./back-end/database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: