version: '3'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./back-end:/app
    depends_on:
      database:
        condition: service_healthy
    command: "dev"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./front-end:/app

  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cashforce_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./back-end/database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  db_data: